#!/usr/bin/python3
import os, sys, lib, readline
try:
	args=sys.argv
	if len(args)==1:
		print("""\033[1;32m
      :::::::::       ::::::::::        :::    :::         :::   :::           :::        :::::::::::       :::  
     :+:    :+:      :+:               :+:    :+:        :+:+: :+:+:        :+: :+:          :+:           :+:   
    +:+    +:+      +:+               +:+    +:+       +:+ +:+:+ +:+      +:+   +:+         +:+           +:+    
   +#++:++#+       :#::+::#          +#++:++#++       +#+  +:+  +#+     +#++:++#++:        +#+           +#+     
  +#+    +#+      +#+               +#+    +#+       +#+       +#+     +#+     +#+        +#+           +#+      
 #+#    #+#      #+#               #+#    #+#       #+#       #+#     #+#     #+#        #+#           #+#       
#########       ###               ###    ###       ###       ###     ###     ###    ###########       ########## 
		\033[0m""")
	salida = None
	def menu():
		global salida
		print("""
	●▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬●
		 1) Generate brute force's dictionary
		 2) Attack service
		99) Exit
	●▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬●
		""")
		salida=""
		salida_boolean=False
		while (salida_boolean==False):
			salida=int(input("choose: "))
			if (salida < 1 or salida > 2) and (salida!=99):
				print("\033[1;31m[-]\033[0m The option "+str(salida)+" doesn't exist")
				salida_boolean=False
			else:
				salida_boolean=True
	menu()
	if salida==1:
		os.system("./dictionary")
	elif salida==2:
		output=None
		output_input=""
		while output==None:
			output_input=str(input("Output: "))
			if output_input=="" or output_input==' ':
				print("\033[1;31m[-]\033[0m Invalid input")
				output=None
			elif output_input=="True":
				file=False
				while file==False:
					dic=input("path: ")
					if os.path.isfile(dic):
						file=True
					else:
						print("\033[1;31m[-]\033[0m File not found")
						file=False
				output=True
			elif output_input=="False":
				print("\033[1;34m[i]\033[0m e.i: password1<<==>>password2...")
				dic=input("dictionary: ")
				output=False
			else:
				print("\033[1;31m[-]\033[0m Invalid value")
				output=None
		os.system("./attack "+str(output)+" '"+str(dic)+"\'")
	elif salida==99:
		print("Good Bye! :)")
		sys.exit()
except KeyboardInterrupt:
	print("Oh! What happened? :O")
except ValueError:
	print("\033[1;31m[-]\033[0m Error at type a value. Incorrect value or you don't type nothing.")
